name: All Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  all-tests:
    runs-on: ubuntu-latest
    name: All Tests

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./mvnw -B -V clean verify
    - name: Upload test artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts-${{ github.run_id }}
        path: |
          target/surefire-reports/**
          target/failsafe-reports/**
          target/playwright-screenshots/**
          target/reports/**
          target/site/**
          target/test.log
        if-no-files-found: ignore
        retention-days: 7
        compression-level: 9
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
    - name: Check clean git state
      run: ./.github/workflows/check-clean-git-state.sh
